name: trashsmart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.0
  carousel_slider: ^2.3.1
  flutter_shapes: ^0.2.1
  adobe_xd: ^1.0.0+1
  persistent_bottom_nav_bar: ^2.1.0
  dotted_border: ^1.0.6
  flutter_countdown_timer: ^1.3.0
  http: ^0.12.2
  json_serializable: ^3.5.0
  lottie: ^0.7.0+1
  webview_flutter: ^1.0.6
  firebase_core: "0.5.2"
  firebase_auth: "^0.18.3"
  cloud_firestore: "^0.14.3"
  firebase_messaging: "^8.0.0-dev.8"
  shared_preferences: ^0.5.12+4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1
  smooth_star_rating: ^1.1.1
  intl: ^0.16.0

  # Add Stack Architecture
  # state management
  stacked: ^1.7.1
  stacked_hooks: 0.1.1+3

  # navigation
  auto_route:
  stacked_services: ^0.4.4+3

  # Bottom Sheet modal
  modal_bottom_sheet: ^1.0.0+1 #later remove and use system default
  # inversion of control
  get_it:
  injectable:
  flutter_hooks:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/logo.png
    - lib/assets/lottie/schedule.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSans
      fonts:
        - asset: lib/assets/fonts/WorkSans-Regular.ttf
        - asset: lib/assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Bold.ttf
        - asset: lib/assets/fonts/Roboto-Regular.ttf
        - asset: lib/assets/fonts/Roboto-Medium.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
